<a href="https://colab.research.google.com/github/davide6556/AML/blob/main/AML_upload_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load your ML dataset

More on [CSV files](https://tools.ietf.org/html/rfc4180).

First of all we need to get the dataset!

* Get CSV files from a local drive directly into Colab

Then, we will explore few common ways to load CSV files into the notebook:

* Load CSV Files with the Python Standard Library
* Load CSV Files with NumPy
* Load CSV Files with Pandas.

Then, we will try one last thing:

* Get CSV files from github and load into pandas

## Get CSV files from a local drive directly into Colab

In [5]:
from google.colab import files
uploaded = files.upload()
# with this method i upload the files i have in my laptop directly in colab

Saving pima-indians-diabetes.data.csv to pima-indians-diabetes.data.csv

## Load CSV Files with the Python Standard Library

In [7]:
import csv
import numpy as np
filename = 'pima-indians-diabetes.data.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x = list(reader) # We have a list of list in the dataset
print(type(x))

In [11]:
x[0:10]

[['6', '148', '72', '35', '0', '33.6', '0.627', '50', '1'],
 ['1', '85', '66', '29', '0', '26.6', '0.351', '31', '0'],
 ['8', '183', '64', '0', '0', '23.3', '0.672', '32', '1'],
 ['1', '89', '66', '23', '94', '28.1', '0.167', '21', '0'],
 ['0', '137', '40', '35', '168', '43.1', '2.288', '33', '1'],
 ['5', '116', '74', '0', '0', '25.6', '0.201', '30', '0'],
 ['3', '78', '50', '32', '88', '31', '0.248', '26', '1'],
 ['10', '115', '0', '0', '0', '35.3', '0.134', '29', '0'],
 ['2', '197', '70', '45', '543', '30.5', '0.158', '53', '1'],
 ['8', '125', '96', '0', '0', '0', '0.232', '54', '1']]

In [ ]:
print(x[0])

['6', '148', '72', '35', '0', '33.6', '0.627', '50', '1']

In [12]:
# we want to have an array, so we tranform the list in this way
mydata_withpython = np.array(x).astype('float')
print(type(mydata_withpython))

<class 'numpy.ndarray'>

In [ ]:
print(mydata_withpython.shape)
# 9 columns and 768 rows
# 1 col will be the column with the label 0/1

(768, 9)

## Load CSV Files with NumPy

In [ ]:
from numpy import loadtxt
filename = 'pima-indians-diabetes.data.csv' # specify the data we want
raw_data = open(filename, 'rt') # we open the file in the mod read text
mydata_withnumpy = loadtxt(raw_data, delimiter=",")

In [ ]:
mydata_withnumpy

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
print(mydata_withnumpy.shape)

(768, 9)

## Load CSV Files with Pandas

In [14]:
from pandas import read_csv
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
mydata_withpandas = read_csv(filename, names=names)
# The function returns a `pandas.DataFrame` that one can immediately process, summarize, plot, etc
# better for visualization
print(type(mydata_withpandas))

In [ ]:
print(mydata_withpandas.shape)

(768, 9)

In [ ]:
mydata_withpandas

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

## Get CSV files from github and load into pandas

In [17]:
import pandas as pd

url = 'https://raw.githubusercontent.com/dbonacorsi/AML-Basic/refs/heads/main/datasets/pima-indians-diabetes.data.csv'

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)
data

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]